In [70]:
import numpy as np

temp = []
temp.append([10, 10, 10])
temp.append([30, 10, 10])
temp.append([10, 5, 30])
temp.append([30, 10, 30])
vertices = np.array(temp)

camera_point = (3, 3, 2)
vertex_vectors = vertices - camera_point


print(vertices[:,1])
print(vertex_vectors[:,1])

multiplier = []

for x in range(np.shape(vertices)[0]):
    multiplier.append(vertices[:,1][x] / vertex_vectors[:,1][x])

multiplier = np.array(multiplier)
print(np.diag(multiplier))
# multiplier = np.atleast_2d(multiplier).T


print(multiplier)

print(np.transpose(vertices))


out = np.matmul(np.transpose(vertex_vectors), np.diag(multiplier))

vertex_transformed = np.transpose(vertices) - out
vertex_transformed = np.transpose(vertex_transformed)
print(vertex_transformed)

[10 10  5 10]
[7 7 2 7]
[[1.42857143 0.         0.         0.        ]
 [0.         1.42857143 0.         0.        ]
 [0.         0.         2.5        0.        ]
 [0.         0.         0.         1.42857143]]
[1.42857143 1.42857143 2.5        1.42857143]
[[10 30 10 30]
 [10 10  5 10]
 [10 10 30 30]]
[[  0.           0.          -1.42857143]
 [ -8.57142857   0.          -1.42857143]
 [ -7.5          0.         -40.        ]
 [ -8.57142857   0.         -10.        ]]


In [4]:
import numpy as np 


test = [1,2,3,5]
# doesn't work
# print(np.array(test).diagonal())

print(np.diag(np.array(test)))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]
